---
- name: Setup Apache webserver
  hosts: vm1
  become: true
  tasks:
  - name: Installing web server
    yum:
      name: httpd
      state: latest

  - name: Start and enable the web server
    service:
      name: httpd
      state: started
      enabled: true

