---
- name: Connect to VM
  hosts: vm1
  tasks:
    - name: Create a directory
      file:
        path: /home/philip_gurango/myshare
        state: directory
        mode: 0750

    - name: Create a file (touch)
      file:        
        path: /home/philip_gurango/myshare/touched_file
        state: touch
        mode: 0640

