---
- name: Connect to VM
  hosts: vm1
  gather_facts: no
  tasks:
  - name: create a new file with lineinfile
    lineinfile: 
      dest: /tmp/test.conf 
      line: ''
      state: present
      create: True

  - name: add a string to the new file
    lineinfile: 
      dest: /tmp/test.conf
      line: 'Hello, World!'
      state: present

  - name: add a string to the END of file
    lineinfile: 
      dest: /tmp/test.conf
      insertafter: EOF
      line: This is the LAST line

  - name: add a string to the BOF of file
    lineinfile: 
      dest: /tmp/test.conf
      insertbefore: BOF
      line: This is the FIRST line
      

# This is the FIRST line
#
# Hello, World!
# This is the LAST line