---
- name: Conditional based on boolean
  hosts: vm1
  vars:
    memory: "{{ansible_memory_mb.real.total}}"   #ansible_memtotal_mb
  tasks:
    - name: Display
      debug:
        msg: "{{memory}}"

    - name: "mariadb being installed conditionally."
      yum:
        name: mariadb-server
        state: latest
      when: memory >= 400   # reduce this to 400

# NOTE: Other operators can be ==, !=, <, > <= >= etc

