---
- name: Conditional based on an item in a list
  hosts: vm1
  vars:
    username: jason

    userlist:
      - devops
      - root
      - student
      - philip

  tasks:
    - name: Create a User and assign him to the wheel group
      user:
        name: "{{username}}"
        groups: wheel
        append: yes
      when: username in userlist  

